Update patch set 2
Patch Set 2: Verified-1 Code-Review-1

This patch breaks build on payton:

error: VNDK library: libz's ABI has INCOMPATIBLE CHANGES Please check compatiblity report at: /home/android/los16.0_xt1900/out/soong/.intermediates/external/zlib/libz/android_arm64_armv8-a_kryo_vendor_shared/libz.so.abidiff

Patch-set: 2
Reviewer: Gerrit User 20370 <20370@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=-1
Label: Code-Review=-1